### ISSUE TITLE
Not working for IPV6

### ISSUE THREAD

**Issue by msrl2000** [gmencz/OneClip#3]
Hi
The app is working based on shared IPV4 behind NAT. 
while IPV6 users are having a public unique ipv6 for each device.
your website\server is answering ipv6 and it kills the functionality of the website for dual stack users.

3 alternatives offered:
1. drop ipv6 support on your server (it will serve only ipv4)
2. add ipv6 prefix for /64 or even /56, assume that 2 computer from the same prefix /64 are from the same network.
3. add the option the change the URL after the domain and randomize it, as https://drop.lol did for the same reason.

good luck

**Comment by gmencz** [comment]
Thank you for the solutions offered, will look into it!

**Comment by msrl2000** [comment]
thanks!
so cool!
